import { useEffect, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { ArrowLeft, Camera, FileText, Plus, X } from 'lucide-react'
import { useAuth, type EmployeeDetails } from '../lib/store'
import { formatCurrency } from '../lib/utils'

type Tab='resume'|'private'|'salary'|'security'

export default function EmployeeProfile(){
  const {id}=useParams();const navigate=useNavigate()
  const {user,employees,getEmployeeDetails,updateEmployeeDetails,updateEmployee,uploadAvatar,updatePayrollWage,changePassword}=useAuth()
  const employeeId=id||user?.employeeId||''
  const employee=employees.find(item=>item.id===employeeId)
  const own=user?.employeeId===employeeId;const manager=user?.role==='admin'||user?.role==='hr'
  const [tab,setTab]=useState<Tab>('resume');const [details,setDetails]=useState<EmployeeDetails|null>(null);const [loading,setLoading]=useState(true)
  const [editing,setEditing]=useState(false);const [message,setMessage]=useState('');const [error,setError]=useState('')
  const [publicForm,setPublicForm]=useState({about:'',jobLove:'',interests:'',phone:'',location:'',skills:[] as string[],certifications:[] as string[]})
  const [privateForm,setPrivateForm]=useState<Record<string,string>>({});const [bankForm,setBankForm]=useState<Record<string,string>>({})
  const [wage,setWage]=useState(0);const [salaryConfig,setSalaryConfig]=useState<Record<string,any>>({})
  const [password,setPassword]=useState({current:'',next:'',confirm:''})
  async function load(){if(!employeeId)return;setLoading(true);const result=await getEmployeeDetails(employeeId);setLoading(false);if(!result.ok||!result.details){setError(result.error||'Profile unavailable');return}setDetails(result.details);const e=result.details.employee;setPublicForm({about:e.about||'',jobLove:e.jobLove||'',interests:e.interests||'',phone:e.phone||'',location:e.location||'',skills:e.skills||[],certifications:e.certifications||[]});setPrivateForm(result.details.privateInfo||{});setBankForm(result.details.bankDetails||{});setWage(Number(result.details.salaryConfig?.monthlyWage||e.salary||0));setSalaryConfig(result.details.salaryConfig||{})}
  useEffect(()=>{load()},[employeeId])
  if(!employee)return <div className="bg-white border border-line rounded-xl p-8 text-center"><div className="font-medium">Employee not found</div><Link to="/employees" className="text-[12px] underline">Return to directory</Link></div>
  const tabs:[Tab,string][]=[['resume','Resume'],...((own||manager)?[['private','Private information'] as [Tab,string]]:[]),...(manager?[['salary','Salary configuration'] as [Tab,string]]:[]),...(own?[['security','Security'] as [Tab,string]]:[])]
  const savePublic=async()=>{setError('');const result=await updateEmployee(employeeId,publicForm);if(!result.ok)setError(result.error||'Save failed');else{setMessage('Profile saved to PostgreSQL');setEditing(false);await load()}}
  const savePrivate=async()=>{setError('');const result=await updateEmployeeDetails(employeeId,{privateInfo:privateForm,bankDetails:manager?bankForm:undefined});if(!result.ok)setError(result.error||'Save failed');else{setMessage('Private information saved');await load()}}
  const saveSalary=async()=>{setError('');const result=await updatePayrollWage(employeeId,wage,salaryConfig);if(!result.ok)setError(result.error||'Salary update failed');else{setMessage('Salary structure recalculated');await load()}}
  const addTag=(key:'skills'|'certifications')=>{const value=prompt(`Add ${key==='skills'?'a skill':'a certification'}`)?.trim();if(!value)return;if(publicForm[key].some(item=>item.toLowerCase()===value.toLowerCase())){setError('That item already exists');return}setPublicForm({...publicForm,[key]:[...publicForm[key],value]});setEditing(true)}
  return <div className="space-y-5">
    <button onClick={()=>navigate('/employees')} className="text-[12px] text-muted flex items-center gap-1"><ArrowLeft className="w-4 h-4"/>Employee directory</button>
    <section className="bg-white border border-line rounded-xl p-5 flex flex-wrap items-center gap-5">
      <div className="relative"><img src={employee.avatar} className="w-20 h-20 rounded-2xl object-cover bg-paper"/><label className={`${own||manager?'':'hidden'} absolute -right-2 -bottom-2 w-8 h-8 rounded-full bg-ink text-white grid place-items-center cursor-pointer`}><Camera className="w-4 h-4"/><input className="hidden" type="file" accept="image/jpeg,image/png,image/webp" onChange={async e=>{const file=e.target.files?.[0];if(file){const result=await uploadAvatar(employeeId,file);if(!result.ok)setError(result.error||'Upload failed');else{setMessage('Profile picture updated');await load()}}}}/></label></div>
      <div className="flex-1 min-w-[220px]"><div className="text-[11px] uppercase tracking-[.1em] text-muted">{employee.loginId||employee.id}</div><h1 className="text-[23px] font-semibold">{employee.name}</h1><p className="text-[13px] text-muted">{employee.role} • {employee.department} • {employee.location||'Bengaluru'}</p><p className="text-[11px] text-muted mt-1">{employee.email} • {employee.phone||'No phone listed'}</p></div>
      <div className="text-right"><span className="inline-flex px-2 py-1 rounded-md bg-accent-soft border border-[#d6e8db] text-accent text-[11px] font-medium">{employee.status}</span><div className="text-[11px] text-muted mt-2">Joined {employee.joinDate}</div></div>
    </section>
    <div className="flex gap-1 overflow-auto border-b border-line">{tabs.map(([key,label])=><button key={key} onClick={()=>setTab(key)} className={`px-4 py-2.5 text-[12px] whitespace-nowrap border-b-2 ${tab===key?'border-ink text-ink font-medium':'border-transparent text-muted'}`}>{label}</button>)}</div>
    {message&&<div className="text-[11px] text-accent bg-accent-soft border border-[#d6e8db] rounded-lg px-3 py-2">{message}</div>}{error&&<div className="text-[11px] text-[#991b1b] bg-[#fdf2f2] border border-[#f0d6d6] rounded-lg px-3 py-2">{error}</div>}
    {loading?<div className="bg-white border border-line rounded-xl p-10 text-center text-[12px] text-muted">Loading secured profile…</div>:<>
    {tab==='resume'&&<div className="grid lg:grid-cols-3 gap-4"><section className="lg:col-span-2 bg-white border border-line rounded-xl p-5 space-y-5">
      <div className="flex justify-between"><h2 className="text-[14px] font-semibold">Public profile</h2>{(own||manager)&&<button onClick={()=>editing?savePublic():setEditing(true)} className="px-3 py-1.5 rounded-lg bg-ink text-white text-[11px]">{editing?'Save changes':'Edit profile'}</button>}</div>
      {([['about','About me'],['jobLove','What I love about my job'],['interests','Interests']] as const).map(([key,label])=><div key={key}><label className="text-[11px] uppercase tracking-[.06em] text-muted">{label}</label>{editing?<textarea value={publicForm[key]} onChange={e=>setPublicForm({...publicForm,[key]:e.target.value})} maxLength={500} className="mt-1 w-full min-h-20 p-3 rounded-lg border border-line bg-paper text-[12px]"/>:<p className="mt-1 text-[13px] leading-relaxed">{publicForm[key]||'Not added yet.'}</p>}</div>)}
      {(['skills','certifications'] as const).map(key=><div key={key}><div className="flex justify-between"><label className="text-[11px] uppercase tracking-[.06em] text-muted">{key}</label>{(own||manager)&&<button onClick={()=>addTag(key)} className="text-[11px] flex items-center gap-1"><Plus className="w-3 h-3"/>Add</button>}</div><div className="mt-2 flex flex-wrap gap-2">{publicForm[key].map(item=><span key={item} className="px-2.5 py-1 rounded-md border border-line bg-paper text-[11px]">{item}{editing&&<button onClick={()=>setPublicForm({...publicForm,[key]:publicForm[key].filter(x=>x!==item)})} className="ml-1"><X className="inline w-3 h-3"/></button>}</span>)}{!publicForm[key].length&&<span className="text-[12px] text-muted">None added</span>}</div></div>)}
    </section><aside className="bg-white border border-line rounded-xl p-5 h-fit"><h2 className="text-[14px] font-semibold">Work information</h2>{[['Manager',employee.manager||'—'],['Company',employee.company||'—'],['Department',employee.department],['Location',employee.location||'—']].map(([k,v])=><div key={k} className="py-3 border-b border-line last:border-0"><div className="text-[10px] text-muted uppercase">{k}</div><div className="text-[12px] font-medium mt-1">{v}</div></div>)}</aside></div>}
    {tab==='private'&&details&&<div className="grid lg:grid-cols-2 gap-4"><InfoForm title="Private information" values={privateForm} onChange={setPrivateForm} fields={[['dateOfBirth','Date of birth'],['residentialAddress','Residential address'],['mailingAddress','Mailing address'],['nationality','Nationality'],['personalEmail','Personal email'],['gender','Gender'],['maritalStatus','Marital status'],['emergencyContact','Emergency contact']]} disabled={false}/><InfoForm title="Bank details" values={bankForm} onChange={setBankForm} fields={[['accountNumber','Account number'],['bankName','Bank name'],['ifscCode','IFSC code'],['pan','PAN'],['uan','UAN'],['employeeCode','Employee code']]} disabled={!manager}/><button onClick={savePrivate} className="lg:col-span-2 py-2 rounded-lg bg-ink text-white text-[12px]">Save permitted private information</button><div className="lg:col-span-2 bg-white border border-line rounded-xl p-5"><h3 className="text-[13px] font-semibold">Documents</h3><div className="mt-3 grid sm:grid-cols-2 gap-2">{details.documents.map(doc=><a key={doc.id} href={doc.url} target="_blank" className="border border-line rounded-lg p-3 flex gap-2 text-[12px]"><FileText className="w-4 h-4"/><span className="truncate">{doc.name}</span></a>)}{!details.documents.length&&<span className="text-[12px] text-muted">No documents uploaded.</span>}</div></div></div>}
    {tab==='salary'&&manager&&<section className="bg-white border border-line rounded-xl p-5"><h2 className="text-[14px] font-semibold">Salary structure</h2><p className="text-[11px] text-muted mt-1">Manager-only configuration. Components are validated server-side and recalculated in PostgreSQL.</p><div className="mt-4 grid sm:grid-cols-2 lg:grid-cols-4 gap-3"><NumberField label="Monthly wage" value={wage} set={setWage}/>{['workingDaysPerWeek','breakMinutes','pfEmployeePercent','pfEmployerPercent','professionalTax'].map(key=><NumberField key={key} label={key.replace(/([A-Z])/g,' $1')} value={Number(salaryConfig[key]||0)} set={value=>setSalaryConfig({...salaryConfig,[key]:value})}/>)}</div><div className="mt-4 grid sm:grid-cols-2 lg:grid-cols-3 gap-2">{(salaryConfig.components||[]).map((component:any,index:number)=><div key={component.id} className="border border-line bg-paper rounded-lg p-3"><div className="text-[11px] font-medium">{component.name}</div><div className="text-[10px] text-muted">{component.type}</div><input type="number" value={component.value} onChange={e=>{const components=[...salaryConfig.components];components[index]={...component,value:Number(e.target.value)};setSalaryConfig({...salaryConfig,components})}} className="mt-2 w-full p-2 border border-line rounded-md text-[12px]"/></div>)}</div><button onClick={saveSalary} className="mt-4 px-4 py-2 rounded-lg bg-accent text-white text-[12px]">Save and recalculate {formatCurrency(wage)}</button></section>}
    {tab==='security'&&own&&<section className="bg-white border border-line rounded-xl p-5 max-w-xl"><h2 className="text-[14px] font-semibold">Change password</h2><div className="mt-4 space-y-3">{(['current','next','confirm'] as const).map(key=><input key={key} type="password" placeholder={key==='current'?'Current password':key==='next'?'New password':'Confirm new password'} value={password[key]} onChange={e=>setPassword({...password,[key]:e.target.value})} className="w-full p-3 border border-line bg-paper rounded-lg text-[12px]"/>)}<button onClick={async()=>{if(password.next!==password.confirm){setError('New passwords do not match');return}const result=await changePassword(password.current,password.next);result.ok?setMessage('Password changed'):setError(result.error||'Password change failed')}} className="px-4 py-2 rounded-lg bg-ink text-white text-[12px]">Update password</button></div></section>}
    </>}</div>
}

function InfoForm({title,values,onChange,fields,disabled}:{title:string;values:Record<string,string>;onChange:(value:Record<string,string>)=>void;fields:[string,string][];disabled:boolean}){return <section className="bg-white border border-line rounded-xl p-5"><h2 className="text-[14px] font-semibold">{title}</h2><div className="mt-4 grid sm:grid-cols-2 gap-3">{fields.map(([key,label])=><label key={key} className={key.includes('Address')?'sm:col-span-2':''}><span className="text-[10px] uppercase text-muted">{label}</span><input disabled={disabled} type={key==='dateOfBirth'?'date':'text'} value={values[key]||''} onChange={e=>onChange({...values,[key]:e.target.value})} className="mt-1 w-full p-2.5 border border-line bg-paper rounded-lg text-[12px] disabled:opacity-60"/></label>)}</div>{disabled&&<p className="mt-3 text-[10px] text-muted">View-only. HR/admin controls bank changes.</p>}</section>}
function NumberField({label,value,set}:{label:string;value:number;set:(value:number)=>void}){return <label><span className="text-[10px] uppercase text-muted">{label}</span><input type="number" min="0" value={value} onChange={e=>set(Number(e.target.value))} className="mt-1 w-full p-2.5 border border-line bg-paper rounded-lg text-[12px]"/></label>}
